services:

  backend:
    build:
      context: ./backend/galactic-tournament-api
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend/galactic-tournament-ui
    ports:
      - "4200:80"
    depends_on:
      - backend